organisation('org.codehaus.groovy').module('groovy').required('default,optional')

organisation('org.apache.ivy').module('ivy').required()
organisation('commons-logging').module('commons-logging').required()
organisation('com.h2database').module('h2').required()
organisation('org.jasypt').module('jasypt').required()
organisation('net.sf.opencsv').module('opencsv').required()
organisation('nekohtml').module('nekohtml').required()